matrix:
  include:
    - language: go
      go: 1.12.6
      script:
        - make build

    - language: node_js
      node_js: 10.16.0
      before_script:
        - npm install -g vuepress
      script:
        - set -e
        - vuepress build docs
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        local_dir: docs/.vuepress/dist
        fqdn: https://docs.commercio.network
        committer_from_gh: true
        on:
          branch: master

