version: '3'

services:
  cndnode0:
    container_name: cndnode0
    image: "commercionetwork/cndnode"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=${LOG:-cnd.log}
    volumes:
      - ./build:/cnd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  cndnode1:
    container_name: cndnode1
    image: "commercionetwork/cndnode"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=${LOG:-cnd.log}
    volumes:
      - ./build:/cnd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  cndnode2:
    container_name: cndnode2
    image: "commercionetwork/cndnode"
    environment:
      - ID=2
      - LOG=${LOG:-cnd.log}
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build:/cnd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  cndnode3:
    container_name: cndnode3
    image: "commercionetwork/cndnode"
    environment:
      - ID=3
      - LOG=${LOG:-cnd.log}
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build:/cnd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

  cnclinode0:
    container_name: cnclinode0
    image: "commercionetwork/cnclirest"
    environment:
      - ID=0
      - LOGCNCLI=${LOG:-cnd.cli.log}
    volumes:
      - ./build:/cnd:Z
    networks:
      - localnet

  proxy-nginx:
    container_name:   proxy-nginx
    image: "nginx"
    ports:
      - "7123:7123"
      - "7124:7124"
    volumes:
      - ./build/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - localnet

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.10.0/16

